# Generated by Django 5.0.4 on 2024-05-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('job_positions', models.CharField(max_length=50)),
                ('job_details', models.TextField()),
            ],
        ),
    ]
