# Generated by Django 5.0.4 on 2024-05-14 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_news_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_slug',
        ),
    ]
